2017-03-26T23:51:30.539829+00:00 app[web.1]: [2017-03-26 23:51:30 +0000] [4] [INFO] Using worker: sync
2017-03-26T23:51:30.547065+00:00 app[web.1]: [2017-03-26 23:51:30 +0000] [9] [INFO] Booting worker with pid: 9
2017-03-26T23:51:30.613911+00:00 app[web.1]: [2017-03-26 23:51:30 +0000] [10] [INFO] Booting worker with pid: 10
2017-03-26T23:51:31.287853+00:00 heroku[web.1]: Starting process with command `gunicorn app:app`
2017-03-26T23:51:31.296793+00:00 app[web.1]:  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2017-03-26T23:51:31.305700+00:00 app[web.1]:  * Restarting with stat
2017-03-26T23:51:31.317001+00:00 app[web.1]: [2017-03-26 23:51:31 +0000] [9] [ERROR] Exception in worker process
2017-03-26T23:51:31.317004+00:00 app[web.1]: Traceback (most recent call last):
2017-03-26T23:51:31.317008+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/arbiter.py", line 578, in spawn_worker
2017-03-26T23:51:31.317009+00:00 app[web.1]:     worker.init_process()
2017-03-26T23:51:31.317010+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/workers/base.py", line 126, in init_process
2017-03-26T23:51:31.317010+00:00 app[web.1]:     self.load_wsgi()
2017-03-26T23:51:31.317011+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/workers/base.py", line 135, in load_wsgi
2017-03-26T23:51:31.317012+00:00 app[web.1]:     self.wsgi = self.app.wsgi()
2017-03-26T23:51:31.317013+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
2017-03-26T23:51:31.317014+00:00 app[web.1]:     self.callable = self.load()
2017-03-26T23:51:31.317014+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
2017-03-26T23:51:31.317015+00:00 app[web.1]:     return self.load_wsgiapp()
2017-03-26T23:51:31.317016+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
2017-03-26T23:51:31.317017+00:00 app[web.1]:     return util.import_app(self.app_uri)
2017-03-26T23:51:31.317017+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/util.py", line 376, in import_app
2017-03-26T23:51:31.317018+00:00 app[web.1]:     __import__(module)
2017-03-26T23:51:31.317018+00:00 app[web.1]:   File "/app/app.py", line 140, in <module>
2017-03-26T23:51:31.317019+00:00 app[web.1]:     app.run(debug=True)
2017-03-26T23:51:31.317019+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 841, in run
2017-03-26T23:51:31.317020+00:00 app[web.1]:     run_simple(host, port, self, **options)
2017-03-26T23:51:31.317021+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/werkzeug/serving.py", line 717, in run_simple
2017-03-26T23:51:31.317021+00:00 app[web.1]:     s.bind((hostname, port))
2017-03-26T23:51:31.317022+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/socket.py", line 228, in meth
2017-03-26T23:51:31.317022+00:00 app[web.1]:     return getattr(self._sock,name)(*args)
2017-03-26T23:51:31.317023+00:00 app[web.1]: error: [Errno 98] Address already in use
2017-03-26T23:51:31.317408+00:00 app[web.1]: [2017-03-26 23:51:31 +0000] [9] [INFO] Worker exiting (pid: 9)
2017-03-26T23:51:31.748643+00:00 app[web.1]: [2017-03-26 23:51:31 +0000] [10] [INFO] Worker exiting (pid: 10)
2017-03-26T23:51:31.764891+00:00 app[web.1]: [2017-03-26 23:51:31 +0000] [17] [INFO] Listening at: http://0.0.0.0:46603 (17)
2017-03-26T23:51:31.765001+00:00 app[web.1]: [2017-03-26 23:51:31 +0000] [17] [INFO] Using worker: sync
2017-03-26T23:51:31.776230+00:00 app[web.1]: [2017-03-26 23:51:31 +0000] [21] [INFO] Booting worker with pid: 21
2017-03-26T23:51:31.764374+00:00 app[web.1]: [2017-03-26 23:51:31 +0000] [17] [INFO] Starting gunicorn 19.7.0
2017-03-26T23:51:31.872864+00:00 app[web.1]: [2017-03-26 23:51:31 +0000] [23] [INFO] Booting worker with pid: 23
2017-03-26T23:51:32.044852+00:00 app[web.1]:  * Debugger is active!
2017-03-26T23:51:32.047312+00:00 app[web.1]:  * Debugger PIN: 414-935-665
2017-03-26T23:51:32.151504+00:00 app[web.1]:  * Debugger is active!
2017-03-26T23:51:32.152074+00:00 app[web.1]:  * Debugger PIN: 414-935-665
2017-03-26T23:51:32.171007+00:00 app[web.1]: [2017-03-26 23:51:32 +0000] [23] [INFO] Worker exiting (pid: 23)
2017-03-26T23:51:32.171690+00:00 app[web.1]: [2017-03-26 23:51:32 +0000] [17] [INFO] Handling signal: term
2017-03-26T23:51:32.172098+00:00 app[web.1]: Exception SystemExit: 0 in <module 'threading' from '/app/.heroku/python/lib/python2.7/threading.pyc'> ignored
2017-03-26T23:51:32.242027+00:00 app[web.1]: [2017-03-26 23:51:32 +0000] [4] [INFO] Shutting down: Master
2017-03-26T23:51:32.242218+00:00 app[web.1]: [2017-03-26 23:51:32 +0000] [4] [INFO] Reason: Worker failed to boot.
2017-03-26T23:51:32.157886+00:00 heroku[web.1]: Stopping all processes with SIGTERM
2017-03-26T23:51:32.382227+00:00 heroku[web.1]: Process exited with status 3
2017-03-26T23:51:33.411058+00:00 app[web.1]: [2017-03-26 23:51:33 +0000] [4] [INFO] Starting gunicorn 19.7.0
2017-03-26T23:51:33.411459+00:00 app[web.1]: [2017-03-26 23:51:33 +0000] [4] [INFO] Listening at: http://0.0.0.0:34262 (4)
2017-03-26T23:51:33.411584+00:00 app[web.1]: [2017-03-26 23:51:33 +0000] [4] [INFO] Using worker: sync
2017-03-26T23:51:33.415453+00:00 app[web.1]: [2017-03-26 23:51:33 +0000] [9] [INFO] Booting worker with pid: 9
2017-03-26T23:51:33.511248+00:00 app[web.1]: [2017-03-26 23:51:33 +0000] [10] [INFO] Booting worker with pid: 10
2017-03-26T23:51:34.003874+00:00 app[web.1]:  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2017-03-26T23:51:34.005486+00:00 app[web.1]: Traceback (most recent call last):
2017-03-26T23:51:34.005489+00:00 app[web.1]:     worker.init_process()
2017-03-26T23:51:34.005488+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/arbiter.py", line 578, in spawn_worker
2017-03-26T23:51:34.005489+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/workers/base.py", line 126, in init_process
2017-03-26T23:51:34.005493+00:00 app[web.1]:     self.callable = self.load()
2017-03-26T23:51:34.005494+00:00 app[web.1]:     return self.load_wsgiapp()
2017-03-26T23:51:34.005493+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
2017-03-26T23:51:34.005491+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/workers/base.py", line 135, in load_wsgi
2017-03-26T23:51:34.005490+00:00 app[web.1]:     self.load_wsgi()
2017-03-26T23:51:34.005495+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
2017-03-26T23:51:34.005492+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
2017-03-26T23:51:34.005495+00:00 app[web.1]:     return util.import_app(self.app_uri)
2017-03-26T23:51:34.005496+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/util.py", line 376, in import_app
2017-03-26T23:51:34.005484+00:00 app[web.1]: [2017-03-26 23:51:34 +0000] [10] [ERROR] Exception in worker process
2017-03-26T23:51:34.005496+00:00 app[web.1]:     __import__(module)
2017-03-26T23:51:34.005497+00:00 app[web.1]:   File "/app/app.py", line 140, in <module>
2017-03-26T23:51:34.005491+00:00 app[web.1]:     self.wsgi = self.app.wsgi()
2017-03-26T23:51:34.005497+00:00 app[web.1]:     app.run(debug=True)
2017-03-26T23:51:34.005500+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/socket.py", line 228, in meth
2017-03-26T23:51:34.005498+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 841, in run
2017-03-26T23:51:34.005500+00:00 app[web.1]:     s.bind((hostname, port))
2017-03-26T23:51:34.005499+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/werkzeug/serving.py", line 717, in run_simple
2017-03-26T23:51:34.005501+00:00 app[web.1]:     return getattr(self._sock,name)(*args)
2017-03-26T23:51:34.005499+00:00 app[web.1]:     run_simple(host, port, self, **options)
2017-03-26T23:51:34.005502+00:00 app[web.1]: error: [Errno 98] Address already in use
2017-03-26T23:51:34.007209+00:00 app[web.1]:  * Restarting with stat
2017-03-26T23:51:34.005661+00:00 app[web.1]: [2017-03-26 23:51:34 +0000] [10] [INFO] Worker exiting (pid: 10)
2017-03-26T23:51:34.278608+00:00 app[web.1]: [2017-03-26 23:51:34 +0000] [17] [INFO] Starting gunicorn 19.7.0
2017-03-26T23:51:34.278980+00:00 app[web.1]: [2017-03-26 23:51:34 +0000] [17] [INFO] Listening at: http://0.0.0.0:34262 (17)
2017-03-26T23:51:34.279064+00:00 app[web.1]: [2017-03-26 23:51:34 +0000] [17] [INFO] Using worker: sync
2017-03-26T23:51:34.462701+00:00 app[web.1]:  * Debugger is active!
2017-03-26T23:51:34.283629+00:00 app[web.1]: [2017-03-26 23:51:34 +0000] [21] [INFO] Booting worker with pid: 21
2017-03-26T23:51:34.464437+00:00 app[web.1]:  * Debugger PIN: 225-910-626
2017-03-26T23:51:34.332960+00:00 app[web.1]: [2017-03-26 23:51:34 +0000] [22] [INFO] Booting worker with pid: 22
2017-03-26T23:51:34.455615+00:00 app[web.1]: [2017-03-26 23:51:34 +0000] [9] [INFO] Worker exiting (pid: 9)
2017-03-26T23:51:34.501857+00:00 app[web.1]:  * Debugger PIN: 225-910-626
2017-03-26T23:51:34.501422+00:00 app[web.1]:  * Debugger is active!
2017-03-26T23:51:34.997672+00:00 app[web.1]: [2017-03-26 23:51:34 +0000] [4] [INFO] Reason: Worker failed to boot.
2017-03-26T23:51:34.997573+00:00 app[web.1]: [2017-03-26 23:51:34 +0000] [4] [INFO] Shutting down: Master
2017-03-26T23:51:34.892853+00:00 heroku[web.1]: State changed from starting to up
2017-03-26T23:51:35.060103+00:00 heroku[web.1]: Process exited with status 3
2017-03-26T23:51:35.074513+00:00 heroku[web.1]: State changed from up to crashed
2017-03-26T23:52:05.533873+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=moolaa.herokuapp.com request_id=c49f56a2-289d-4743-b3e2-eb741cd53f68 fwd="128.237.178.82" dyno= connect= service= status=503 bytes= protocol=https
2017-03-26T23:52:05.678194+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=moolaa.herokuapp.com request_id=06b9d8e1-85d6-48c2-ac88-bb4dd93d5ffe fwd="128.237.178.82" dyno= connect= service= status=503 bytes= protocol=https
2017-03-26T23:52:06.781399+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=moolaa.herokuapp.com request_id=9448307f-573b-477b-9dc9-07a340126c9a fwd="128.237.178.82" dyno= connect= service= status=503 bytes= protocol=https
2017-03-26T23:52:06.904818+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=moolaa.herokuapp.com request_id=3315d98d-e61b-4508-b3a5-aa9603c0b93c fwd="128.237.178.82" dyno= connect= service= status=503 bytes= protocol=https
